version: '3'

services:
  app:
    build: .
    image: puttanapoom/app:1.1.0 # update 1.2.0 and in terminal
    container_name: my_app_1.1.0
    ports:
      - "8081:1337" # ภายนอก:ภายใน 1.0 8080/1337
    environment:
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=${DATABASE_HOST}
      # - DATABASE_HOST=db
      - DATABASE_PORT=${DATABASE_PORT}
      # - DATABASE_PORT=5432
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_SSL=false
    depends_on: 
      - db
    restart: always
    #  - serviceName
  db:
    image: postgres:latest
    container_name: my_db
    ports:
      #- ${DATABASE_PORT}=5432
      - 5437:5432 # ภายนอก:ภายใน 1.0 5436
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      

